apps/comment/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from .views import AddcommentView, NotificationView, mark_to_read, mark_to_delete

urlpatterns = [
    url(r'^add/$', AddcommentView, name='add_comment'),
    url(r'^notification/$', NotificationView, name='notification'),
    url(r'^notification/no-read/$', NotificationView, {'is_read': 'false'}, name='notification_no_read'),
    url(r'^notification/mark-to-read/$', mark_to_read, name='mark_to_read'),
    url(r'^notification/mark-to-delete/$', mark_to_delete, name='mark_to_delete'),
]

izone/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.views.generic import TemplateView

from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import ArticleSitemap, CategorySitemap, TagSitemap
from blog.feeds import AllArticleRssFeed

from rest_framework.routers import DefaultRouter
from api import views as api_views

if settings.API_FLAG:
    router = DefaultRouter()
    router.register(r'users',api_views.UserListSet)
    router.register(r'articles',api_views.ArticleListSet)
    router.register(r'tags',api_views.TagListSet)
    router.register(r'categorys',api_views.CategoryListSet)
    router.register(r'timelines',api_views.TimelineListSet)
    router.register(r'toollinks',api_views.ToolLinkListSet)

# 网站地图
sitemaps = {
    'articles': ArticleSitemap,
    'tags': TagSitemap,
    'categories': CategorySitemap
}

urlpatterns = [
    url(r'^adminx/', admin.site.urls),
    url(r'^accounts/', include('allauth.urls')),  # allauth
    url(r'^accounts/', include('oauth.urls', namespace='oauth')),  # oauth,只展现一个用户登录界面
    url('', include('blog.urls', namespace='blog')),  # blog
    url(r'^comment/',include('comment.urls',namespace='comment')), # comment
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')), # robots
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'), # 网站地图
    url(r'^feed/$', AllArticleRssFeed(), name='rss'),   # rss订阅
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 加入这个才能显示media文件

if settings.API_FLAG:
    urlpatterns.append(url(r'^api/v1/',include(router.urls,namespace='api')))    # restframework

if settings.TOOL_FLAG:
    urlpatterns.append(url(r'^tool/', include('tool.urls',namespace='tool')))    # tool

apps/comment/models.py
from django.db import models
from django.conf import settings
from blog.models import Article

import markdown
import emoji


class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='%(class)s_related', verbose_name='评论人')
    create_date = models.DateTimeField('创建时间', auto_now_add=True)
    content = models.TextField('评论内容')
    parent = models.ForeignKey('self', verbose_name='父评论', related_name='%(class)s_child_comments', blank=True,
                               null=True)
    rep_to = models.ForeignKey('self', verbose_name='回复', related_name='%(class)s_rep_comments', blank=True, null=True)

    class Meta:
        '''这是一个元类，用来继承的'''
        abstract = True

    def __str__(self):
        return self.content[:20]

    def content_to_markdown(self):
        # 先转换成emoji然后转换成markdown,'escape':所有原始HTML将被转义并包含在文档中
        to_emoji_content = emoji.emojize(self.content, use_aliases=True)
        to_md = markdown.markdown(to_emoji_content,
                                  safe_mode='escape',
                                  extensions=[
                                      'markdown.extensions.extra',
                                      'markdown.extensions.codehilite',
                                  ])
        return to_md

class ArticleComment(Comment):
    belong = models.ForeignKey(Article, related_name='article_comments', verbose_name='所属文章')

    class Meta:
        verbose_name = '文章评论'
        verbose_name_plural = verbose_name
        ordering = ['create_date']

class Notification(models.Model):
    create_p = models.ForeignKey(settings.AUTH_USER_MODEL,verbose_name='提示创建者',related_name='notification_create')
    get_p = models.ForeignKey(settings.AUTH_USER_MODEL,verbose_name='提示接收者',related_name='notification_get')
    comment = models.ForeignKey(ArticleComment,verbose_name='所属评论',related_name='the_comment')
    create_date = models.DateTimeField('提示时间',auto_now_add=True)
    is_read = models.BooleanField('是否已读',default=False)

    def mark_to_read(self):
        self.is_read = True
        self.save(update_fields=['is_read'])

    class Meta:
        verbose_name = '提示信息'
        verbose_name_plural = verbose_name
        ordering = ['-create_date']

    def __str__(self):
        return '{}@了{}'.format(self.create_p,self.get_p)

apps/comment/views.py
from django.shortcuts import render
from blog.models import Article
from .models import ArticleComment, Notification
from django.conf import settings
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from datetime import datetime
from django.shortcuts import get_object_or_404
from . import handlers

user_model = settings.AUTH_USER_MODEL


@login_required
@require_POST
def AddcommentView(request):
    if request.is_ajax():
        data = request.POST
        new_user = request.user
        new_content = data.get('content')
        article_id = data.get('article_id')
        rep_id = data.get('rep_id')
        the_article = Article.objects.get(id=article_id)
        if not rep_id:
            new_comment = ArticleComment(author=new_user, content=new_content, belong=the_article, parent=None,
                                         rep_to=None)
        else:
            new_rep_to = ArticleComment.objects.get(id=rep_id)
            new_parent = new_rep_to.parent if new_rep_to.parent else new_rep_to
            new_comment = ArticleComment(author=new_user, content=new_content, belong=the_article, parent=new_parent,
                                         rep_to=new_rep_to)
        new_comment.save()
        new_point = '#com-' + str(new_comment.id)
        return JsonResponse({'msg': '评论提交成功！', 'new_point': new_point})
    return JsonResponse({'msg': '评论失败！'})


@login_required
def NotificationView(request, is_read=None):
    '''展示提示消息列表'''
    now_date = datetime.now()
    return render(request, 'comment/notification.html', context={'is_read': is_read, 'now_date': now_date})


@login_required
@require_POST
def mark_to_read(request):
    '''将一个消息标记为已读'''
    if request.is_ajax():
        data = request.POST
        user = request.user
        id = data.get('id')
        info = get_object_or_404(Notification, get_p=user, id=id)
        info.mark_to_read()
        return JsonResponse({'msg': 'mark success'})
    return JsonResponse({'msg': 'miss'})


@login_required
@require_POST
def mark_to_delete(request):
    '''将一个消息删除'''
    if request.is_ajax():
        data = request.POST
        user = request.user
        id = data.get('id')
        info = get_object_or_404(Notification, get_p=user, id=id)
        info.delete()
        return JsonResponse({'msg': 'delete success'})
    return JsonResponse({'msg': 'miss'})

apps/comment/templates/comment/comment_form.html
{% load static %}
<div class="card border-0 rounded-0 f-16" id="editor-block">
    {% if user.is_authenticated %}
    <div class="card-body p-2 p-md-3">
        <textarea class="form-control rounded-0" id="comment-form" name="text"
                  placeholder="评论请使用 markdown 语法" rows="5" required></textarea>
    </div>
    <div class="card-footer border-0 bg-white py-0 px-2 px-md-3" id="editor-footer">
        <button type="button" class="btn btn-info btn-sm float-right f-16"
                id="push-com" data-csrf="{{ csrf_token }}" data-article-id="{{ article.id }}"
                data-ajax-url="{% url 'comment:add_comment' %}">提交评论</button>
        <button class="btn btn-sm py-0 px-2" id="emoji-btns" type="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-smile-o fa-2x"></i>
        </button>
        <div class="dropdown-menu" id='emoji-list' aria-labelledby="emoji-btns">
            <div class="editor-btns px-2" id="emojis">
                <button class="btn p-1"><img
                        src="{% static 'comment/emoji/stuck_out_tongue_winking_eye.png' %}"
                        title="stuck_out_tongue_winking_eye" alt="emoji-stuck_out_tongue_winking_eye"
                        data-emoji=":stuck_out_tongue_winking_eye:"></button>
                <button class="btn p-1"><img src="{% static 'comment/emoji/sunglasses.png' %}"
                                             title="sunglasses" alt="emoji-sunglasses"
                                             data-emoji=":sunglasses:"></button>
                <button class="btn p-1"><img src="{% static 'comment/emoji/sweat.png' %}" title="sweat"
                                             alt="emoji-sweat" data-emoji=":sweat:"></button>
                <button class="btn p-1"><img src="{% static 'comment/emoji/sweat_smile.png' %}"
                                             title="sweat_smile" alt="emoji-sweat_smile"
                                             data-emoji=":sweat_smile:"></button>
                <button class="btn p-1"><img src="{% static 'comment/emoji/unamused.png' %}" title="unamused"
                                             alt="emoji-unamused" data-emoji=":unamused:"></button>
                <button class="btn p-1"><img src="{% static 'comment/emoji/v.png' %}" title="v" alt="emoji-v"
                                             data-emoji=":v:"></button>
                <button class="btn p-1"><img src="{% static 'comment/emoji/worried.png' %}" title="worried"
                                             alt="emoji-worried" data-emoji=":worried:"></button>
                <button class="btn p-1"><img src="{% static 'comment/emoji/yum.png' %}" title="yum"
                                             alt="emoji-yum" data-emoji=":yum:"></button>
            </div>
            <div class="editor-btns px-2" id="emojis">
                <button class="btn p-1"><img src="{% static 'comment/emoji/sleepy.png' %}" title="sleepy"
                                             alt="emoji-sleepy" data-emoji=":sleepy:"></button>
                <button class="btn p-1"><img src="{% static 'comment/emoji/smile.png' %}" title="smile"
                                             alt="emoji-smile" data-emoji=":smile:"></button>
                <button class="btn p-1"><img src="{% static 'comment/emoji/smiley.png' %}" title="smiley"
                                             alt="emoji-smiley" data-emoji=":smiley:"></button>
                <button class="btn p-1"><img src="{% static 'comment/emoji/smirk.png' %}" title="smirk"
                                             alt="emoji-smirk" data-emoji=":smirk:"></button>
                <button class="btn p-1"><img src="{% static 'comment/emoji/sob.png' %}" title="sob"
                                             alt="emoji-sob" data-emoji=":sob:"></button>
                <button class="btn p-1"><img src="{% static 'comment/emoji/sparkling_heart.png' %}"
                                             title="sparkling_heart" alt="emoji-sparkling_heart"
                                             data-emoji=":sparkling_heart:"></button>
                <button class="btn p-1"><img src="{% static 'comment/emoji/stuck_out_tongue.png' %}"
                                             title="stuck_out_tongue" alt="emoji-stuck_out_tongue"
                                             data-emoji=":stuck_out_tongue:"></button>
                <button class="btn p-1"><img
                        src="{% static 'comment/emoji/stuck_out_tongue_closed_eyes.png' %}"
                        title="stuck_out_tongue_closed_eyes" alt="emoji-stuck_out_tongue_closed_eyes"
                        data-emoji=":stuck_out_tongue_closed_eyes:"></button>
            </div>
            <div class="editor-btns px-2" id="emojis">
                <button class="btn p-1"><img src="{% static 'comment/emoji/kissing_heart.png' %}"
                                             title="kissing_heart" alt="emoji-kissing_heart"
                                             data-emoji=":kissing_heart:"></button>
                <button class="btn p-1"><img src="{% static 'comment/emoji/mask.png' %}" title="mask"
                                             alt="emoji-mask" data-emoji=":mask:"></button>
                <button class="btn p-1"><img src="{% static 'comment/emoji/no_mouth.png' %}" title="no_mouth"
                                             alt="emoji-no_mouth" data-emoji=":no_mouth:"></button>
                <button class="btn p-1"><img src="{% static 'comment/emoji/pensive.png' %}" title="pensive"
                                             alt="emoji-pensive" data-emoji=":pensive:"></button>
                <button class="btn p-1"><img src="{% static 'comment/emoji/persevere.png' %}" title="persevere"
                                             alt="emoji-persevere" data-emoji=":persevere:"></button>
                <button class="btn p-1"><img src="{% static 'comment/emoji/pray.png' %}" title="pray"
                                             alt="emoji-pray" data-emoji=":pray:"></button>
                <button class="btn p-1"><img src="{% static 'comment/emoji/relieved.png' %}" title="relieved"
                                             alt="emoji-relieved" data-emoji=":relieved:"></button>
                <button class="btn p-1"><img src="{% static 'comment/emoji/scream.png' %}" title="scream"
                                             alt="emoji-scream" data-emoji=":scream:"></button>
            </div>
            <div class="editor-btns px-2" id="emojis">
                <button class="btn p-1"><img src="{% static 'comment/emoji/grin.png' %}" title="grin"
                                             alt="emoji-grin" data-emoji=":grin:"></button>
                <button class="btn p-1"><img src="{% static 'comment/emoji/heart.png' %}" title="heart"
                                             alt="emoji-heart" data-emoji=":heart:"></button>
                <button class="btn p-1"><img src="{% static 'comment/emoji/heartbeat.png' %}" title="heartbeat"
                                             alt="emoji-heartbeat" data-emoji=":heartbeat:"></button>
                <button class="btn p-1"><img src="{% static 'comment/emoji/heart_eyes.png' %}"
                                             title="heart_eyes" alt="emoji-heart_eyes"
                                             data-emoji=":heart_eyes:"></button>
                <button class="btn p-1"><img src="{% static 'comment/emoji/hushed.png' %}" title="hushed"
                                             alt="emoji-hushed" data-emoji=":hushed:"></button>
                <button class="btn p-1"><img src="{% static 'comment/emoji/innocent.png' %}" title="innocent"
                                             alt="emoji-innocent" data-emoji=":innocent:"></button>
                <button class="btn p-1"><img src="{% static 'comment/emoji/joy.png' %}" title="joy"
                                             alt="emoji-joy" data-emoji=":joy:"></button>
                <button class="btn p-1"><img src="{% static 'comment/emoji/kissing_closed_eyes.png' %}"
                                             title="kissing_closed_eyes" alt="emoji-kissing_closed_eyes"
                                             data-emoji=":kissing_closed_eyes:"></button>

            </div>
            <div class="editor-btns px-2" id="emojis">
                <button class="btn p-1"><img src="{% static 'comment/emoji/cry.png' %}" title="cry"
                                             alt="emoji-cry" data-emoji=":cry:"></button>
                <button class="btn p-1"><img src="{% static 'comment/emoji/disappointed_relieved.png' %}"
                                             title="disappointed_relieved" alt="emoji-disappointed_relieved"
                                             data-emoji=":disappointed_relieved:"></button>
                <button class="btn p-1"><img src="{% static 'comment/emoji/dizzy_face.png' %}"
                                             title="dizzy_face" alt="emoji-dizzy_face"
                                             data-emoji=":dizzy_face:"></button>
                <button class="btn p-1"><img src="{% static 'comment/emoji/dog.png' %}" title="dog"
                                             alt="emoji-dog" data-emoji=":dog:"></button>
                <button class="btn p-1"><img src="{% static 'comment/emoji/fearful.png' %}" title="fearful"
                                             alt="emoji-fearful" data-emoji=":fearful:"></button>
                <button class="btn p-1"><img src="{% static 'comment/emoji/fist.png' %}" title="fist"
                                             alt="emoji-fist" data-emoji=":fist:"></button>
                <button class="btn p-1"><img src="{% static 'comment/emoji/flushed.png' %}" title="flushed"
                                             alt="emoji-flushed" data-emoji=":flushed:"></button>
                <button class="btn p-1"><img src="{% static 'comment/emoji/frowning.png' %}" title="frowning"
                                             alt="emoji-frowning" data-emoji=":frowning:"></button>

            </div>
            <div class="editor-btns px-2" id="emojis">
                <button class="btn p-1"><img src="{% static 'comment/emoji/+1.png' %}" title="+1"
                                             alt="emoji-+1" data-emoji=":+1:"></button>
                <button class="btn p-1"><img src="{% static 'comment/emoji/angry.png' %}" title="angry"
                                             alt="emoji-angry" data-emoji=":angry:"></button>
                <button class="btn p-1"><img src="{% static 'comment/emoji/anguished.png' %}" title="anguished"
                                             alt="emoji-anguished" data-emoji=":anguished:"></button>
                <button class="btn p-1"><img src="{% static 'comment/emoji/blush.png' %}" title="blush"
                                             alt="emoji-blush" data-emoji=":blush:"></button>
                <button class="btn p-1"><img src="{% static 'comment/emoji/broken_heart.png' %}"
                                             title="broken_heart" alt="emoji-broken_heart"
                                             data-emoji=":broken_heart:"></button>
                <button class="btn p-1"><img src="{% static 'comment/emoji/clap.png' %}" title="clap"
                                             alt="emoji-clap" data-emoji=":clap:"></button>
                <button class="btn p-1"><img src="{% static 'comment/emoji/cold_sweat.png' %}"
                                             title="cold_sweat" alt="emoji-cold_sweat"
                                             data-emoji=":cold_sweat:"></button>
                <button class="btn p-1"><img src="{% static 'comment/emoji/confounded.png' %}"
                                             title="confounded" alt="emoji-confounded"
                                             data-emoji=":confounded:"></button>


            </div>
        </div>
    </div>
    {% else %}
    <div class="card-body text-center m-2 m-md-3 f-16" id="no-editor">
        <div>您尚未登录，请
            <a class="text-danger" href="{% url 'account_login' %}?next={{ request.path }}">登录</a> 或
            <a class="text-danger" href="{% url 'account_signup' %}?next={{ request.path }}">注册</a> 后评论
        </div>
        <div class="login-link mt-2">
            <a class="mx-3" href="/accounts/weibo/login/?next={{ request.path }}" title="社交账号登录有点慢，请耐心等候！"><i
                    class="fa fa-weibo fa-2x"></i></a>
            <a class="mx-3" href="/accounts/github/login/?next={{ request.path }}" title="社交账号登录有点慢，请耐心等候！"><i
                    class="fa fa-github fa-2x"></i></a>
        </div>
    </div>
    {% endif %}
</div>

apps/comment/templates/comment/comment_list.html
{% load comment_tags oauth_tags %}
{% load humanize %}

<div class="card-body p-2 p-md-3 f-17" id="comment-list">
    <ul class="list-unstyled">
        <div class="mb-3">
            <strong>{% get_comment_user_count article %}&nbsp;人参与&nbsp;|&nbsp;{% get_comment_count article %}&nbsp;条评论</strong>
        </div>
        {% for comment in comment_list %}
        <div class="comment-parent pt-2" id="com-{{ comment.id }}">
            <li class="media">
                {% get_user_avatar_tag comment.author %}
                <div class="media-body ml-2">
                    <a class="float-right small mr-2 rep-btn" href="#editor-block"
                       data-repid="{{ comment.id }}" data-repuser="{{ comment.author.username }}">回复</a>
                    <p class="mt-0 mb-1">
                        <strong>{{ comment.author }}</strong>
                        {% if comment.author.is_superuser %}
                        <small class="text-danger">[博主]</small>
                        {% endif %}
                    </p>
                    <p class="small text-muted">{{ forloop.counter }}楼&nbsp;-&nbsp;{{ comment.create_date|naturaltime }}</p>
                </div>
            </li>
            <div class="comment-body">{{ comment.content_to_markdown|safe }}</div>
        </div>
        {% get_child_comments comment as child_comments %}
        {% if child_comments %}
        <ul class="list-unstyled ml-4">
            {% for each in child_comments %}
            <div class="comment-child pt-2" id="com-{{ each.id }}">
                <li class="media">
                    {% get_user_avatar_tag each.author %}
                    <div class="media-body ml-2">
                        <a class="float-right small mr-2 rep-btn" href="#editor-block"
                           data-repid="{{ each.id }}" data-repuser="{{ each.author.username }}">回复</a>
                        <p class="mt-0 mb-1"><strong>{{ each.author }}</strong>
                            {% if each.author.is_superuser %}
                            <small class="text-danger">[博主]</small>
                            {% endif %}
                            <i class="fa fa-share"></i>
                            @{{ each.rep_to.author.username }}
                        </p>
                        <p class="small text-muted">{{ each.create_date|naturaltime }}</p>
                    </div>
                </li>
                <div class="comment-body">{{ each.content_to_markdown|safe }}</div>
            </div>
            {% endfor %}
        </ul>
        {% endif %}
        {% empty %}
        暂时没有评论，欢迎来尬聊！
        {% endfor %}
    </ul>
</div>

apps/comment/templates/comment/notification.html
{% extends 'blog/base.html' %}
{% load static %}
{% load humanize %}
{% load comment_tags %}

{% block head_title %}个人信息推送{% endblock %}

{% block top-file %}
<link href="{% static 'comment/css/notification.css' %}?v=5" rel="stylesheet">
{% endblock %}

{% block base_content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 col-lg-9">
            {% get_notifications user is_read as notifications %}
            <ul class="cbp_tmtimeline f-16">
                {% for each in notifications %}
                <li>
                    <time class="cbp_tmtime" datetime="{{ each.create_date }}">
                        <span>{{ each.create_date|date:"Y/m/d"}}</span>
                        <span>{{ each.create_date|date:"H:i"}}</span>
                    </time>
                    <div class="cbp_tmicon"><i class="fa fa-envelope"></i></div>
                    <div class="cbp_tmlabel">
                        <h2>
                            <strong>{{ each.create_p }}</strong>&nbsp;在&nbsp;
                            <a class="text-info" title="查看评论详情"
                               href="{{ each.comment.belong.get_absolute_url }}#com-{{ each.comment.id }}">
                                {{ each.comment.belong.title }}</a>&nbsp;中@了你，并评论道：
                        </h2>
                        <p>{{ each.comment.content|truncatechars:130 }}</p>
                        {% if not each.is_read %}
                        <div class="to_read pb-1">
                            <button class="btn btn-success float-right rounded-0 f-16" data-id="{{ each.id }}"
                                    data-csrf="{{ csrf_token }}" data-url="{% url 'comment:mark_to_read' %}">标为已读
                            </button>
                        </div>
                        {% else %}
                        <div class="to_delete pb-1">
                            <button class="btn btn-danger float-right rounded-0 f-16" data-id="{{ each.id }}"
                                    data-csrf="{{ csrf_token }}" data-url="{% url 'comment:mark_to_delete' %}">删除信息
                            </button>
                        </div>
                        {% endif %}
                    </div>
                </li>
                {% empty %}
                <li>
                    <time class="cbp_tmtime" datetime="{{ now_date }}">
                        <span>{{ now_date|date:"Y/m/d"}}</span>
                        <span>{{ now_date|date:"H:i"}}</span>
                    </time>
                    <div class="cbp_tmicon"><i class="fa fa-envelope"></i></div>
                    <div class="cbp_tmlabel">
                        <h2>你暂时没有任何推送消息！</h2>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-md-4 col-lg-3">
            <div class="card rounded-0 border-0" id="notes-main">
                <div class="card-header bg-white border-0">
                    <h4><strong><i class="fa fa-bell-o mr-1"></i>&nbsp;提示信息</strong></h4>
                </div>
                <div class="card-body pt-0 url-menu">
                    <ul class="list-group">
                        {% url 'comment:notification' as all_url %}
                        {% url 'comment:notification_no_read' as no_read_url %}
                        <a class="list-group-item rounded-0 {% if request.path == all_url %}active{% endif %}"
                           href="{{ all_url }}">全部信息
                            <span class="badge float-right">{% get_notifications_count user %}</span>
                        </a>
                        <a class="list-group-item rounded-0 {% if request.path == no_read_url %}active{% endif %}"
                           href="{{ no_read_url }}">未读信息
                            <span class="badge float-right">{% get_notifications_count user 'false' %}</span>
                        </a>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block end_file %}
<script src="{% static 'comment/js/notification.js' %}?v=23"></script>
{% endblock %}